US11 US12 #166 Excluir e Editar Postagem
fga-eps-mds/2020.1-VC_Usuario pull request #173
Opened 2020-11-05 03:50 UTC by Bruno-Felix

## Descrição
- Funcionalidade de o usuário Editar Postagem;
- Funcionalidade de o usuário Excluir Postagem;
- Padronizando mensagem de erro das controller postage e UPS.

## _Issue_ Relacionada
#166

## Como Isso Foi Testado?
Usando o console do terminal e a ferramenta Insomnia.

## Capturas de Tela (se apropriado):

## Tipos de Mudanças
- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [x] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [ ] Documentação.

2020-11-06 01:04 UTC, emysdias commented on src/controllers/postage_controller.js
> +            return res.status(400).send({error_delete_one: err.message});
Acho q tem muito console.log durante todos os arquivos, acho q é bom pra auxiliar, mas acho q deve ser retirado depois para não flodar o terminal com print

2020-11-06 01:23 UTC, emysdias commented
Ta dando muitos erros, ta dando usuário indefinido, quando vou criar uma postagem o botão de anonimo fica on e quando vou mudar ele atualiza a página e dá erros consequentes a isso, depois deem uma olhada nisso

2020-11-06 01:24 UTC, emysdias commented
Não sei se é só na minha máquina ou os bugs estão nessa branch

2020-11-06 13:18 UTC, Bruno-Felix commented
> Ta dando muitos erros, ta dando usuário indefinido, quando vou criar uma postagem o botão de anonimo fica on e quando vou mudar ele atualiza a página e dá erros consequentes a isso, depois deem uma olhada nisso

Usuário indefinido está falando sobre erro no vue? Na minha branch não gera esse erro.

O erro de atualização constante não cabe a nossa issue. O erro está na página do perfil e já foi conversado que foi resolvido em outra issue.

2020-11-06 14:48 UTC, emysdias commented
> > Ta dando muitos erros, ta dando usuário indefinido, quando vou criar uma postagem o botão de anonimo fica on e quando vou mudar ele atualiza a página e dá erros consequentes a isso, depois deem uma olhada nisso
> 
> Usuário indefinido está falando sobre erro no vue? Na minha branch não gera esse erro.
> 
> O erro de atualização constante não cabe a nossa issue. O erro está na página do perfil e já foi conversado que foi resolvido em outra issue.

O erro em si q está dando é q tudo está dando indefinido, ai quando crio uma postagem e vou pra home fica tudo branco, isso quando consigo criar uma postagem, e o do usuário foi uma observação q teve pois está atualizando com a branch de editar e excluir perfil, só q não funciona na sua branch. Ai não sei se o problema está sendo só aqui comigo, vou ver se o Denys consegue revisar, vai ver aqui q ta bugando o negócio

2020-11-06 15:17 UTC, emysdias commented on src/routes.js
> +router.delete('/postage/delete_for_test/:id', Postage.delete_one_for_test);
Aqui o nome devia seguir o padrão, ou delete_one ou delete

2020-11-06 15:18 UTC, emysdias commented on src/routes.js
> +router.put('/postage/delete_one', UPS.check_exist_user_and_postage, Postage.check_postage_is_not_anon, Postage.check_user_of_postage, Postage.delete_one);
pq esse delete ficou como put?

2020-11-06 15:22 UTC, emysdias reviewed
Ta funcionando no back ok, acho q só no front q ta dando esses problemas

2020-11-06 15:35 UTC, emysdias commented
No insomnia funcionou a rota delete for test, acho q só falta o feedback lá tipo "Deletado com sucesso", a do put eu não entendi pq é um put e ta com delete one, mas não recebe parametro de ID, ai no front ficaria confuso

2020-11-06 15:42 UTC, emysdias commented
![image](https://user-images.githubusercontent.com/52640974/98385118-641a6280-202d-11eb-9d3a-a52b90909b13.png)

Eu falei sobre o usuário indefinido pq na develop ta tudo normal, mas nessa branch q dá usuário indefinido

2020-11-06 17:36 UTC, Bruno-Felix commented on src/routes.js
> +router.delete('/postage/delete_for_test/:id', Postage.delete_one_for_test);
Modifiquei o nome porque era uma rota pra teste. Muito provavelmente vamos retira-la do projeto por não ter função pratica dentro da aplicação. Não é usada em nenhum lugar a não ser em testes.

2020-11-06 17:37 UTC, Bruno-Felix commented on src/routes.js
> +router.put('/postage/delete_one', UPS.check_exist_user_and_postage, Postage.check_postage_is_not_anon, Postage.check_user_of_postage, Postage.delete_one);
Então por que o método delete não tem body. E as infos que passamos são por body.

2020-11-06 17:47 UTC, Bruno-Felix commented
> No insomnia funcionou a rota delete for test, acho q só falta o feedback lá tipo "Deletado com sucesso"

Essa rota é meramente teste, não mexemos nela a não ser o nome para não confundir...

2020-11-06 17:48 UTC, Bruno-Felix commented
> > > Ta dando muitos erros, ta dando usuário indefinido, quando vou criar uma postagem o botão de anonimo fica on e quando vou mudar ele atualiza a página e dá erros consequentes a isso, depois deem uma olhada nisso
> > 
> > 
> > Usuário indefinido está falando sobre erro no vue? Na minha branch não gera esse erro.
> > O erro de atualização constante não cabe a nossa issue. O erro está na página do perfil e já foi conversado que foi resolvido em outra issue.
> 
> O erro em si q está dando é q tudo está dando indefinido, ai quando crio uma postagem e vou pra home fica tudo branco, isso quando consigo criar uma postagem, e o do usuário foi uma observação q teve pois está atualizando com a branch de editar e excluir perfil, só q não funciona na sua branch. Ai não sei se o problema está sendo só aqui comigo, vou ver se o Denys consegue revisar, vai ver aqui q ta bugando o negócio

@DenysRogeres Pode testar isso? No meu não está dando isso. Até pq não mexemos com a criação e nem listagem das postagem

2020-11-06 18:54 UTC, DenysRogeres commented
> > > > Ta dando muitos erros, ta dando usuário indefinido, quando vou criar uma postagem o botão de anonimo fica on e quando vou mudar ele atualiza a página e dá erros consequentes a isso, depois deem uma olhada nisso
> > > 
> > > 
> > > Usuário indefinido está falando sobre erro no vue? Na minha branch não gera esse erro.
> > > O erro de atualização constante não cabe a nossa issue. O erro está na página do perfil e já foi conversado que foi resolvido em outra issue.
> > 
> > 
> > O erro em si q está dando é q tudo está dando indefinido, ai quando crio uma postagem e vou pra home fica tudo branco, isso quando consigo criar uma postagem, e o do usuário foi uma observação q teve pois está atualizando com a branch de editar e excluir perfil, só q não funciona na sua branch. Ai não sei se o problema está sendo só aqui comigo, vou ver se o Denys consegue revisar, vai ver aqui q ta bugando o negócio
> 
> @DenysRogeres Pode testar isso? No meu não está dando isso. Até pq não mexemos com a criação e nem listagem das postagem

Acabei de testar e obtive os seguintes resultados: ao subir a aplicação pela primeiro vez consegui fazer uma nova postagem e apareceu tanto na página de perfil quanto na home. Ao dar refresh na página ou tentar fazer outra postagem, todas as postagens (tanto da home, quanto do perfil) somem. Verifiquei também que após esse problema, na página de perfil é mostrado apenas a pontuação, o nome e as postagem desaparecem. Ao sair da conta, tudo volta ao normal (pelo menos as postagem aparecem na home mesmo após o refresh).

2020-11-06 18:58 UTC, DenysRogeres commented
![Captura de tela de 2020-11-06 15-38-46](https://user-images.githubusercontent.com/54676096/98404139-cdf43580-2048-11eb-8359-50ae9f370b79.png)
Minha tela de perfil fica desta forma

2020-11-06 19:04 UTC, DenysRogeres requested changes
Os problemas comentados devem ser corrigidos

2020-11-06 19:06 UTC, DenysRogeres reviewed
Alguns problemas devem ser corrigidos

2020-11-06 20:34 UTC, Bruno-Felix commented
> Os problemas comentados devem ser corrigidos

Que Problemas?

Voce pediu review mas não apontou aonde.

2020-11-06 20:35 UTC, Bruno-Felix commented
> ![Captura de tela de 2020-11-06 15-38-46](https://user-images.githubusercontent.com/54676096/98404139-cdf43580-2048-11eb-8359-50ae9f370b79.png)
> Minha tela de perfil fica desta forma

Uma tela com nenhuma postagem.

2020-11-06 20:50 UTC, DenysRogeres commented
> > ![Captura de tela de 2020-11-06 15-38-46](https://user-images.githubusercontent.com/54676096/98404139-cdf43580-2048-11eb-8359-50ae9f370b79.png)
> > Minha tela de perfil fica desta forma
> 
> Uma tela com nenhuma postagem. Se puder explicar melhor ficaria grato.
Havia comentado cima, mas os problemas basicamente são: a postagem feita só aparece na home e no perfil na primeira vez, a partir da segunda postagem ou após dar refresh na página, tudo que foi feito até então não é mostrado na home e nem no perfil do usuário. Também observei que ao sair da conta, as postagem feitas aparecem na home e tudo volta-se ao normal.

2020-11-06 20:53 UTC, DenysRogeres commented
Home antes do refresh:
![Captura de tela de 2020-11-06 15-43-45](https://user-images.githubusercontent.com/54676096/98413681-cccb0480-2058-11eb-8f8f-66f8e6dae3f4.png)
Home depois do refresh:

![Captura de tela de 2020-11-06 15-39-05](https://user-images.githubusercontent.com/54676096/98413654-c046ac00-2058-11eb-80fd-3ee910c55edc.png)

2020-11-06 20:55 UTC, DenysRogeres commented
Perfil antes do refresh:
![Captura de tela de 2020-11-06 15-44-10](https://user-images.githubusercontent.com/54676096/98413854-229fac80-2059-11eb-8962-822d2807e079.png)
Perfil depois do refresh:
![Captura de tela de 2020-11-06 15
-38-46](https://user-images.githubusercontent.com/54676096/98413864-259a9d00-2059-11eb-814e-5915f7e49d14.png)

2020-11-06 20:56 UTC, DenysRogeres commented
A postagem feita só aparece na home e no perfil na primeira vez, a partir da segunda postagem ou após dar refresh na página tudo que foi feito até então não é mostrado na home e nem no perfil do usuário. Também observei que ao sair da conta, as postagem feitas voltam a aparece e tudo volta-se ao normal.

2020-11-06 21:19 UTC, DanielPortods commented
Notei que a branch dessa issue no Front-end foi atualizada com a develop. Mas não vi nenhum commit de atualização aqui no Back-end.
O problema so usuário indefinido pode estar ocorrendo por conta disso.

2020-11-06 22:09 UTC, Bruno-Felix commented
> Notei que a branch dessa issue no Front-end foi atualizada com a develop. Mas não vi nenhum commit de atualização aqui no Back-end.
> O problema so usuário indefinido pode estar ocorrendo por conta disso.

No back não gerou conflito.

O problema está no merge feito no front para resolver conflito.

2020-11-07 17:38 UTC, DenysRogeres commented
Acabei de faze a revisão com os novos commits e não encontrei nenhuma inconsistência.

2020-11-07 17:40 UTC, DenysRogeres approved these changes
Agora tá shoow! Parabéns

2020-11-07 17:54 UTC, emysdias approved these changes
Agora sim deu tudo certo, parabéns 🏆

2020-11-07 17:54 UTC, merged